services:
  php:
    container_name: php
    image: php
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:80"
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_SERVER=${SQLSERVER}
      - SQL_DATABASE=${SQL_DATABASE}
      # A comma separated list of fields in the POST sent to the server in store in the database
      - POST_DATUM=${POST_DATUM}
