services:
  php:
    container_name: php
    image: php
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:80"
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_SERVER=${SQL_SERVER}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_TABLE=${SQL_TABLE}
      # A comma separated list of fields in the POST sent to the server to store in the database
      - POST_KEYS=${POST_KEYS}
      # The key to authenticate clients
      - SUBMISSION_PSK=${SUBMISSION_PSK}
